name = "hello_world"
version = "0.1.0"
defaultTargets = ["ChessRules", "ChessTests", "BasicProofs", "HowManyRooks", "TwoKingNoCheckmate", "FunctionDefinition", "TwoRookLadderMateTests", "NextWhiteMoveIsLegal"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.30.0-rc2"

[[lean_lib]]
name = "ChessRules"
srcDir = "Chess"

[[lean_lib]]
name = "ChessTests"
srcDir = "Chess"

[[lean_lib]]
name = "BasicProofs"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "HowManyRooks"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "TwoKingNoCheckmate"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "FunctionDefinition"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TwoRookLadderMateTests"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "NextWhiteMoveIsLegal"
srcDir = "Chess/proofs/two_rook_ladder_mate"
