name = "hello_world"
version = "0.1.0"
defaultTargets = ["ChessRules", "ChessTests", "BasicProofs", "HowManyRooks", "TwoKingNoCheckmate", "TRC_FunctionWithInvariant", "TwoRookLadderMateTests", "NextWhiteMoveIsLegal", "Preservation"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.30.0-rc2"

[[lean_lib]]
name = "ChessRules"
srcDir = "Chess"

[[lean_lib]]
name = "ChessTests"
srcDir = "Chess"

[[lean_lib]]
name = "BasicProofs"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "HowManyRooks"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "TwoKingNoCheckmate"
srcDir = "Chess/proofs"

[[lean_lib]]
name = "TRC_FunctionWithInvariant"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Invariant_SimpleCases"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Invariant_PieceLocations"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Q_Lemma"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Invariant_BlackEmpty"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Invariant_Preservation.lean"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TRC_Invariant_CheckLocations.lean"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "TwoRookLadderMateTests"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "HelperLemmas"
srcDir = "Chess/proofs/two_rook_ladder_mate"

[[lean_lib]]
name = "NextWhiteMoveIsLegal"
srcDir = "Chess/proofs/two_rook_ladder_mate"

