import FunctionDefinition

-- The move selected by the ladder procedure is always legal.
theorem nextWhiteMove_isLegal {n : Nat} {board : Board n}
    {rank : Fin n} {φ : LadderPhase}
    (lsh : LadderShape board rank φ) :
    IsLegalMove board
      (nextWhiteMove lsh).1 (nextWhiteMove lsh).2 := by
  sorry
  -- ----------------------------------------------------------------
  -- PROOF SKETCH
  -- ----------------------------------------------------------------
  -- `IsLegalMove board src dst` expands to two conjuncts:
  --   A. The piece at src belongs to the side to move (White) and its
  --      geometry is valid (rook: clear line; king: one-step).
  --   B. `IsLegalSetup (applyMove board src dst)`, which itself splits:
  --      B1. Exactly one White King exists on the new board.
  --      B2. Exactly one Black King exists on the new board.
  --      B3. `¬ IsCheck b' .White`  (b'.turn = Black after applyMove,
  --          so b'.turn.opponent = White; i.e., White was not left in
  --          check by its own move).
  --
  -- We proceed by case analysis on `φ`.  In each case we first unfold
  -- `LadderShape` to obtain named hypotheses:
  --   ht       : board.turn = .White
  --   hK       : board (kingPos rank hbnd) = some ⟨.White, .King⟩
  --   hRb      : board (rookBPos rank φ hbnd) = some ⟨.White, .Rook⟩
  --   hRa      : board (rookAPos rank φ hbnd) = some ⟨.White, .Rook⟩
  --   huniq    : all squares with a White piece are K, Rb, Ra
  --   hbk      : ∃! bp, board bp = some ⟨.Black, .King⟩
  --   hbk_above: ∀ bp, board bp = some ⟨.Black, .King⟩ →
  --                rookAPos.1 < bp.1          -- Black King above rookA's rank
  --   honly_k  : ∀ p k, board p = some ⟨.Black, k⟩ → k = .King
  --   hsetup   : IsLegalSetup board
  --              (which includes ¬ IsCheck board .Black, because it is
  --               White's turn and the invariant forbids the opponent
  --               to be in check at the start of a move)
  --
  -- ── Case φ = moveRb ─────────────────────────────────────────────
  -- src = (rank, 1)   dst = (rank+1, 1)   (Rook B moves one rank up)
  --
  -- Goal A (right disjunct): board src = some ⟨.White, .Rook⟩  by hRb.
  --   ValidRookMove: src and dst share column 1; they are adjacent
  --   ranks, so no square lies strictly *between* them → path clear. ✓
  --   (Rewrite board.turn via ht.)
  --
  -- Goal B1: White King is still uniquely at (rank, 0) — untouched. ✓
  --
  -- Goal B2: dst = (rank+1, 1) was empty before the move (no capture):
  --   • Not a White piece: huniq places all White pieces at K, Rb, Ra,
  --     none of which equals (rank+1, 1) in phase moveRb.
  --   • Not the Black King: hbk_above gives rookAPos.1 = rank+1 < bp.1,
  --     so the Black King is strictly above rank+1 and cannot be at
  --     rank+1. ✓
  --   Since no piece was at dst, the Black King is still unique. ✓
  --
  -- Goal B3: After the move, b'.turn = Black.  White King is at
  --   (rank, 0).  The only Black piece is the Black King, at some row
  --   > rank+1.  Row difference from rank is ≥ 2 > 1, so the Black
  --   King is not adjacent to the White King → no check. ✓
  --
  -- ── Case φ = moveRa ─────────────────────────────────────────────
  -- src = (rank+1, 0)   dst = (rank+2, 0)   (Rook A moves one rank up)
  --
  -- Goal A: board src = some ⟨.White, .Rook⟩  by hRa.
  --   ValidRookMove: same column (col 0), adjacent ranks → path clear. ✓
  --
  -- Goal B2 (the interesting part): dst = (rank+2, 0) was empty:
  --   • Not a White piece: huniq (K at (rank,0), Rb at (rank+1,1),
  --     Ra at (rank+1,0) — none equals (rank+2,0)). ✓
  --   • Not the Black King: suppose for contradiction the Black King is
  --     at (rank+2, 0).  Then the White Rook Ra at (rank+1, 0) attacks
  --     it along col 0 with no intervening piece (adjacent ranks).
  --     That means IsCheck board .Black holds.  But hsetup contains
  --     ¬ IsCheck board .Black (White to move, opponent = Black).
  --     Contradiction. ✓
  --
  -- Goals B1, B3: same argument as moveRb case. ✓
  --
  -- ── Case φ = moveK ──────────────────────────────────────────────
  -- src = (rank, 0)   dst = (rank+1, 0)   (King steps one rank up)
  -- In phase moveK the pieces are: K=(rank,0), Rb=(rank+1,1), Ra=(rank+2,0).
  --
  -- Goal A (left disjunct): board src = some ⟨.White, .King⟩  by hK.
  --   ValidKingMove: src ≠ dst (different rows), WithinOne rank (rank+1)
  --   (differ by 1) ✓, WithinOne 0 0 (same column, differ by 0) ✓.
  --
  -- dst = (rank+1, 0) was empty before the king moves there:
  --   • Not Rb (that's at (rank+1, 1), different column). ✓
  --   • Not Ra (that's at (rank+2, 0), different rank). ✓
  --   • Not the Black King: hbk_above gives Ra.1 = rank+2 < bp.1, so
  --     the Black King is strictly above rank+2 and cannot be at
  --     rank+1. ✓
  --   No capture occurs; all three White pieces and the Black King
  --   survive — uniqueness is preserved.
  --
  -- Goal B1: White King is now uniquely at (rank+1, 0). ✓
  -- Goal B2: Black King unchanged (no capture). ✓
  --
  -- Goal B3: After the move, White King at (rank+1, 0).  Black King
  --   is at some row > rank+2, so row difference from rank+1 is ≥ 2.
  --   The Black King cannot attack the White King. ✓
  -- ----------------------------------------------------------------
